import HttpServerMock = require("http-server-mock");

import expect from "../helpers/expect";
import * as awsMock from "../helpers/aws-mocks";
import toolWithServer from "../helpers/tool-runner-helper";

const server = new HttpServerMock();
const run = toolWithServer(server);

describe("Dev-Bot tool AWS deploy", function () {
    this.timeout(5000);

    let iam: awsMock.IamMock;
    let lambda: awsMock.LambdaMock;
    let events: awsMock.CloudWatchEventsMock;

    beforeEach(async () => {
        await server.start();

        iam = new awsMock.IamMock(server);
        lambda = new awsMock.LambdaMock(server);
        events = new awsMock.CloudWatchEventsMock(server);
    });

    afterEach(async () => {
        await server.stop();
    });

    it("pushes a new bot to lambda, if the bot doesn't exist", async () => {
        iam.onGetRole("autogenerated-dev-bot-role").findRole();

        lambda.onGetFunction("testbot").dontFindFunction();
        lambda.onCreateFunction("testbot").succeedWithArn("arn:new-bot");

        events.onListRuleNamesByTarget("arn:new-bot").findNoRuleNames();
        events.onPutRule("dev-bot-trigger-testbot", {
            ScheduleExpression: "rate(1 minute)"
        }).succeedWithArn("arn:new-role");
        lambda.onAddPermission("arn:new-bot", "lambda:InvokeFunction", "events.amazonaws.com").succeed();
        events.onPutTargets("dev-bot-trigger-testbot", {Arn: "arn:new-bot"}).succeed();

        let output = await run("aws-deploy", "testbot", "qwe.js");

        expect(output).to.include("Deploying testbot to AWS");
        expect(output).to.match(/\nDone.\n$/);
    });

    it("updates lambda with the new code, if the bot already exits", async () => {
        iam.onGetRole("autogenerated-dev-bot-role").findRole();
        lambda.onGetFunction("testbot").findFunction("arn:updated-bot");
        lambda.onUpdateFunctionCode("testbot").succeed();
        events.onListRuleNamesByTarget("arn:updated-bot").findRuleNames(["dev-bot-trigger"]);

        let output = await run("aws-deploy", "testbot", "qwe.js");

        expect(output).to.include("Deploying testbot to AWS");
        expect(output).to.match(/\nDone.\n$/);
    });

    // TODO: Test help & version (since we can't unit test them)
});
